export type Category =
  | "Web frameworks"
  | "Terminals"
  | "Editors"
  | "Chat & music"
  | "Browsers"
  | "Productivity"
  | "Desktop";
export type Target = {
  id: string;
  name: string;
  category: Category;
  summary: string;
  format: string;
  method: "Native" | "Framework" | "Client mod" | "Extension" | "Config";
  status: "export" | "planned";
  docs: string;
  install: string;
  limitation: string;
  color: string;
};
const target = (
  id: string,
  name: string,
  category: Category,
  format: string,
  method: Target["method"],
  docs: string,
  install: string,
  summary: string,
  color: string,
  limitation = "",
  status: Target["status"] = "export",
): Target => ({
  id,
  name,
  category,
  format,
  method,
  docs,
  install,
  summary,
  color,
  limitation,
  status,
});
export const targets: Target[] = [
  target(
    "css",
    "CSS variables",
    "Web frameworks",
    "CSS",
    "Framework",
    "https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties",
    'Import theme.css once. Set data-theme="dark" or data-theme="light" on the document root for exported appearances. Use the --ts-* variables in your styles.',
    "The universal foundation. Your tokens, anywhere on the web.",
    "#578dcc",
  ),
  target(
    "scss",
    "Sass / SCSS",
    "Web frameworks",
    "SCSS",
    "Framework",
    "https://sass-lang.com/documentation/at-rules/use/",
    'Use @use "./theme" as theme; then theme.$colors-dark or theme.$colors-light. Include theme.emit("dark") inside your chosen selector to emit CSS custom properties.',
    "Variables, maps, and a module for your Sass workflow.",
    "#c282ad",
  ),
  target(
    "tailwind",
    "Tailwind CSS",
    "Web frameworks",
    "CSS · v4",
    "Framework",
    "https://tailwindcss.com/docs/theme",
    "Import Tailwind first, then theme.css. The file includes semantic @theme inline mappings. Use utilities such as bg-primary, text-primary-foreground, and rounded-lg.",
    "Your design tokens, ready to become utility classes.",
    "#69b4c5",
  ),
  target(
    "shadcn",
    "shadcn/ui",
    "Web frameworks",
    "CSS · Tailwind v4",
    "Framework",
    "https://ui.shadcn.com/docs/theming",
    "Merge theme.css into your Tailwind v4 global stylesheet after imports. Remove conflicting theme declarations. Use your existing shadcn/ui components and toggle .dark on the document root.",
    "Components, charts, and sidebars that feel like your theme.",
    "#52525c",
  ),
  target(
    "tokens",
    "Design tokens",
    "Web frameworks",
    "JSON · DTCG 2025.10",
    "Framework",
    "https://www.designtokens.org/tr/2025.10/format/",
    "Import the per-appearance tokens JSON into a tool that supports the DTCG 2025.10 format. Each appearance is a separate token set.",
    "Typed, portable values for your design toolchain.",
    "#9390c6",
  ),
  target(
    "ghostty",
    "Ghostty",
    "Terminals",
    "Config",
    "Native",
    "https://ghostty.org/docs/features/theme",
    "Copy the theme file to $XDG_CONFIG_HOME/ghostty/themes/ (usually ~/.config/ghostty/themes/). Set theme = <file name> in your Ghostty config and reload it.",
    "Fast, native, and now a little more personal.",
    "#8a85b9",
    "Color scheme only; keeps your font and shell configuration.",
  ),
  target(
    "kitty",
    "kitty",
    "Terminals",
    "CONF",
    "Native",
    "https://sw.kovidgoyal.net/kitty/conf/",
    "Copy the .conf file beside kitty.conf, then add include <file name>. Reload the configuration.",
    "A full ANSI palette, cursor, and selection colors.",
    "#9697ab",
  ),
  target(
    "alacritty",
    "Alacritty",
    "Terminals",
    "TOML",
    "Native",
    "https://alacritty.org/config-alacritty.html",
    "Save the TOML file and add its absolute path to the general.import array in alacritty.toml. Preserve your existing imports.",
    "A compact color scheme for your GPU-powered terminal.",
    "#e59d73",
  ),
  target(
    "wezterm",
    "WezTerm",
    "Terminals",
    "TOML",
    "Native",
    "https://wezterm.org/config/appearance.html",
    "Copy the TOML file to ~/.config/wezterm/colors/. Set config.color_scheme to the name listed under [metadata], then reload.",
    "Coordinated terminal colors across every pane.",
    "#9c83c9",
  ),
  target(
    "windows-terminal",
    "Windows Terminal",
    "Terminals",
    "JSON",
    "Native",
    "https://learn.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes",
    "Add the downloaded scheme object to the schemes array in settings.json. Select it under your profile’s Appearance → Color scheme.",
    "All sixteen colors for your Windows command line.",
    "#6fa9cd",
  ),
  target(
    "iterm2",
    "iTerm2",
    "Terminals",
    "iTermColors",
    "Native",
    "https://iterm2.com/documentation-preferences-profiles-colors.html",
    "Open Settings → Profiles → Colors → Color Presets → Import. Choose the .itermcolors file, then select the imported preset.",
    "Import your palette into your favorite macOS terminal.",
    "#7caf92",
  ),
  target(
    "warp",
    "Warp",
    "Terminals",
    "YAML",
    "Native",
    "https://docs.warp.dev/terminal/appearance/custom-themes/",
    "Place the YAML file in ~/.warp/themes/ (macOS) or ${XDG_DATA_HOME:-$HOME/.local/share}/warp-terminal/themes/ (Linux). Select it in Settings → Appearance.",
    "A theme for your terminal workspace.",
    "#7e9ab8",
    "Color scheme export; app loading has not been verified here.",
  ),
  target(
    "foot",
    "foot",
    "Terminals",
    "INI",
    "Native",
    "https://codeberg.org/dnkl/foot/src/branch/master/foot.ini",
    "Save the theme file. Add include=/absolute/path/to/theme.ini in the main section of foot.ini. Keep it before any [section] headers.",
    "A lightweight Wayland terminal with your palette.",
    "#bab18c",
  ),
  target(
    "termux",
    "Termux",
    "Terminals",
    "Properties",
    "Config",
    "https://wiki.termux.com/wiki/Terminal_Settings",
    "Back up ~/.termux/colors.properties, copy the exported colors.properties there, and run termux-reload-settings.",
    "Your Android terminal, in your own colors.",
    "#7f8b96",
  ),
  target(
    "xresources",
    "Xresources",
    "Terminals",
    "Xresources",
    "Config",
    "https://www.x.org/releases/current/doc/man/man1/xrdb.1.xhtml",
    "Merge the exported color declarations into ~/.Xresources, then load it with xrdb -merge ~/.Xresources. Your terminal must support Xresources color keys.",
    "A shared palette for X11 terminal applications.",
    "#8f9ba8",
  ),
  target(
    "vscode",
    "VS Code",
    "Editors",
    "Theme extension",
    "Native",
    "https://code.visualstudio.com/api/extension-guides/color-theme",
    "Open this export folder in VS Code and press F5 to open an Extension Development Host. Select the theme there. To install permanently, package with @vscode/vsce and use Install from VSIX.",
    "Workbench, syntax, diffs, and integrated terminal.",
    "#739fc5",
  ),
  target(
    "zed",
    "Zed",
    "Editors",
    "JSON",
    "Native",
    "https://zed.dev/docs/themes",
    "Copy the JSON theme family into ~/.config/zed/themes/ and select its appearance from Zed’s theme selector.",
    "A native theme family for your editor.",
    "#8b91a4",
  ),
  target(
    "neovim",
    "Neovim",
    "Editors",
    "Lua",
    "Native",
    "https://neovim.io/doc/user/api.html#nvim_set_hl()",
    "Copy the Lua file to ~/.config/nvim/colors/. Use :colorscheme <file name without .lua>, or add vim.cmd.colorscheme(...) to your init.lua.",
    "Editor UI, syntax groups, diagnostics, and diffs.",
    "#88b097",
    "Common built-in and Tree-sitter groups; plugin-specific highlights may use their own colors.",
  ),
  target(
    "helix",
    "Helix",
    "Editors",
    "TOML",
    "Native",
    "https://docs.helix-editor.com/themes.html",
    'Copy the TOML file to ~/.config/helix/themes/ and set theme = "<file name without .toml>" in config.toml.',
    "Semantic syntax and editor colors for Helix.",
    "#ba93c6",
  ),
  target(
    "sublime",
    "Sublime Text",
    "Editors",
    "sublime-color-scheme",
    "Native",
    "https://www.sublimetext.com/docs/color_schemes.html",
    "Save the file in Packages/User via Preferences → Browse Packages. Select it through UI: Select Color Scheme.",
    "Syntax, selection, and editor surfaces.",
    "#cca370",
    "An editor color scheme; Sublime UI chrome is a separate .sublime-theme format.",
  ),
  target(
    "spicetify",
    "Spicetify",
    "Chat & music",
    "INI + CSS",
    "Client mod",
    "https://spicetify.app/docs/customization/themes",
    "Install Spicetify first. Copy the exported folder into its Themes directory. Run spicetify config current_theme <folder> color_scheme <appearance>, then spicetify apply.",
    "Give Spotify a palette that matches the rest of your world.",
    "#78ae92",
    "Requires Spicetify. Spotify updates can change CSS support; this is a color-focused theme.",
  ),
  target(
    "betterdiscord",
    "BetterDiscord",
    "Chat & music",
    "theme.css",
    "Client mod",
    "https://docs.betterdiscord.app/themes/introduction/quick-start",
    "Install BetterDiscord. Open Settings → Themes → Open Themes Folder, copy the .theme.css file into it, then enable the theme.",
    "Your Discord conversations, in your colors.",
    "#9298d3",
    "Requires BetterDiscord. Discord CSS changes frequently; the exported theme is experimental.",
  ),
  target(
    "vencord",
    "Vencord",
    "Chat & music",
    "theme.css",
    "Client mod",
    "https://vencord.dev/faq/",
    "Use Vencord’s Themes folder and enable the downloaded .theme.css file under Local Themes. You can also paste its CSS into QuickCSS.",
    "The same Discord palette, packaged for Vencord.",
    "#cb9ac5",
    "Requires Vencord. Color rules share the BetterDiscord exporter; client updates may require changes.",
  ),
  target(
    "firefox",
    "Firefox",
    "Browsers",
    "Theme manifest",
    "Native",
    "https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme",
    "For a temporary preview, open about:debugging → This Firefox → Load Temporary Add-on and select manifest.json. Permanent installation requires Mozilla signing/distribution.",
    "Tabs, toolbar, sidebar, and browser chrome.",
    "#ce9774",
    "Browser chrome only. Website content needs a separate site-specific style.",
  ),
  target(
    "chromium",
    "Chrome / Chromium",
    "Browsers",
    "Theme manifest",
    "Native",
    "https://developer.chrome.com/docs/extensions/develop/ui/themes",
    "Open chrome://extensions, enable Developer mode, choose Load unpacked, and select this theme folder. The Chromium theme format can also be tried in compatible browsers such as Brave or Edge.",
    "A shared browser palette for your tabs and toolbar.",
    "#8cafb3",
    "Chrome theme format; Brave and Edge loading must be verified separately. Does not recolor websites.",
  ),
  target(
    "obsidian",
    "Obsidian",
    "Productivity",
    "CSS + manifest",
    "Native",
    "https://docs.obsidian.md/Themes/App+themes/Build+a+theme",
    "Place the theme folder inside your vault’s .obsidian/themes/ directory. Restart Obsidian and select the theme in Settings → Appearance.",
    "Notes, sidebars, and a quieter space to think.",
    "#b19ad1",
    "Native CSS variables; individual plugins may require separate mappings.",
  ),
  target(
    "vivaldi",
    "Vivaldi",
    "Browsers",
    "Theme ZIP",
    "Native",
    "https://help.vivaldi.com/desktop/appearance-customization/browser-themes/",
    "Planned: a native Vivaldi theme package.",
    "Bring your palette to Vivaldi’s browser interface.",
    "#d69899",
    "Exporter not implemented yet.",
    "planned",
  ),
];
// Planned targets stay searchable, but cannot be selected for download.
const planned: [string, string, Category, string, string, string][] = [
  [
    "zen",
    "Zen Browser",
    "Browsers",
    "https://docs.zen-browser.app/mods/zen-mods",
    "Zen Mods and browser chrome",
    "#c0ab98",
  ],
  [
    "stylus",
    "Stylus userstyles",
    "Browsers",
    "https://github.com/openstyles/stylus/wiki/Writing-UserCSS",
    "Maintained styles for individual websites",
    "#a5bf96",
  ],
  [
    "konsole",
    "Konsole",
    "Terminals",
    "https://docs.kde.org/stable5/en/konsole/konsole/",
    "KDE terminal color schemes",
    "#91b7cf",
  ],
  [
    "gnome-terminal",
    "GNOME Terminal",
    "Terminals",
    "https://help.gnome.org/users/gnome-terminal/stable/",
    "GNOME terminal profiles",
    "#919cae",
  ],
  [
    "t3-code",
    "T3 Code",
    "Editors",
    "https://github.com/pingdotgg/t3code",
    "Chat, workspace, and terminal theme imports",
    "#b496d4",
  ],
  [
    "gitcomet",
    "GitComet",
    "Productivity",
    "https://github.com/Auto-Explore/GitComet/blob/main/docs/themes.md",
    "Repository UI, syntax, and commit graph",
    "#a3b9cf",
  ],
  [
    "smartgit",
    "SmartGit",
    "Productivity",
    "https://docs.syntevo.com/SmartGit/Latest/Manual/GUI/AdvancedSettings/Theme-Customization",
    "Git UI and repository states",
    "#95bfa9",
  ],
  [
    "slack",
    "Slack",
    "Chat & music",
    "https://slack.com/help/articles/205166337-Change-your-Slack-theme",
    "Workspace theme colors",
    "#c3a1c8",
  ],
  [
    "gtk",
    "GTK",
    "Desktop",
    "https://docs.gtk.org/gtk4/css-overview.html",
    "GTK desktop application styling",
    "#9db696",
  ],
  [
    "kde",
    "KDE Plasma",
    "Desktop",
    "https://develop.kde.org/docs/plasma/",
    "KDE application color schemes",
    "#8aaec7",
  ],
  [
    "waybar",
    "Waybar",
    "Desktop",
    "https://github.com/Alexays/Waybar/wiki/Styling",
    "A coordinated desktop status bar",
    "#a3afcd",
  ],
  [
    "rofi",
    "Rofi",
    "Desktop",
    "https://github.com/davatorium/rofi/blob/next/doc/rofi-theme.5.markdown",
    "App launcher color and shape tokens",
    "#b0a889",
  ],
];
targets.push(
  ...planned.map(([id, name, category, docs, summary, color]) =>
    target(
      id,
      name,
      category,
      "Planned",
      category === "Browsers" ? "Extension" : "Config",
      docs,
      "This integration is on the roadmap.",
      summary,
      color,
      "Exporter not implemented yet.",
      "planned",
    ),
  ),
);
export const categories: Category[] = [
  "Web frameworks",
  "Terminals",
  "Editors",
  "Chat & music",
  "Browsers",
  "Productivity",
  "Desktop",
];
export const exportTargets = targets.filter((t) => t.status === "export");
export const getTarget = (id: string) => {
  const t = targets.find((t) => t.id === id);
  if (!t) throw new Error(`Unknown target: ${id}`);
  return t;
};
